# Mysql development database configuration

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/adminlms_dev
    username: devuser
    password: devpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true