# Mysql test database configuration

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/adminlms_test
    username: testuser
    password: testpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.springframework.boot.context.config: DEBUG